## Title: Markov Chain and Q-Learning

## Objective

- To understand the concept of a **Markov Chain** and its properties.
- To study the **Markov Decision Process (MDP)** for sequential decision-making.
- To understand the working principle of the **Q-Learning** reinforcement learning algorithm.
- To learn how an agent updates Q-values using rewards and future expected rewards.
- To observe how an agent learns an optimal path through trial and error.
- To gain an introduction to **Deep Q-Learning (DQN)** and its advantages over traditional Q-Learning.



## Theory

## 1. Markov Chain

A **Markov Chain** is a stochastic model that describes transitions between different states where the probability of moving to the next state depends **only on the current state** and not on the sequence of previous states.

This property is known as the **Markov Property**.

### Example

```text
S0 → S1 → S2 → S3
```

The transition from **S2** to **S3** depends only on **S2**.

### Properties of a Markov Chain

1. **State Space**
   - The complete set of possible states.

2. **Transition Probability Matrix**
   - Represents the probability of moving from one state to another.

3. **Stationary Distribution**
   - The long-term probability distribution of occupying each state after many transitions.



## 2. Markov Decision Process (MDP)

A **Markov Decision Process (MDP)** extends a Markov Chain by allowing an **agent** to choose actions.

An MDP consists of:

- **States (S)**
- **Actions (A)**
- **Transition Probability (P)**
- **Reward Function (R)**
- **Discount Factor (γ)**

Unlike a Markov Chain, where transitions occur automatically, the agent decides which action to perform.

The objective is to maximise the cumulative future reward.



## 3. Q-Learning

**Q-Learning** is a **model-free reinforcement learning algorithm**.

The agent learns by interacting with the environment through **trial and error**.

Instead of knowing the environment beforehand, it gradually learns which action is best in every state.

A table called the **Q-table** stores the quality (**Q-value**) of every state-action pair.

Each value represents how good an action is when performed in a particular state.

### Q-Learning Update Equation

\[
Q(s,a) = Q(s,a) + \alpha \left[ R + \gamma \max_{a'} Q(s',a') - Q(s,a) \right]
\]

Where:

- **Q(s,a)** = Current Q-value
- **α (Alpha)** = Learning rate
- **R** = Immediate reward
- **γ (Gamma)** = Discount factor
- **s'** = Next state
- **max Q(s',a')** = Best expected future reward

The equation updates the current Q-value using the received reward and the estimated future reward.



### Working of Q-Learning

1. Start with an empty Q-table.
2. Observe the current state.
3. Select an action.
4. Move to the next state.
5. Receive a reward.
6. Update the Q-value.
7. Repeat until the goal state is reached.
8. Continue for many episodes until the Q-values converge.

Through repeated interactions, the agent learns the optimal policy.



### Example

The whiteboard illustrates a **Grid World** environment where:

- **Initial State:** S0
- **Goal State:** S15
- Some states are obstacles.
- Allowed actions are:
  - ↑ Up
  - ↓ Down
  - ← Left
  - → Right

Initially, every value in the **Q-table** is zero.

After each move:

- The agent receives a reward.
- Positive rewards encourage good actions.
- Negative rewards discourage poor actions.
- The Q-table is updated using the Q-Learning equation.

After sufficient training episodes, the agent discovers the shortest path to the goal.



## Deep Q-Learning (Deep Q-Network)

Traditional **Q-Learning** stores all Q-values inside a **Q-table**.

This approach works well only when the number of states is relatively small.

For large environments such as robotics, autonomous driving, or video games, the Q-table becomes extremely large and impractical.

**Deep Q-Learning (DQN)** replaces the Q-table with a **Deep Neural Network (DNN)**.

Instead of storing every Q-value explicitly, the neural network predicts the Q-value for any given state-action pair.



### Advantages of Deep Q-Learning

- Handles very large state spaces.
- Works directly with high-dimensional inputs such as images.
- Better generalises to unseen states.
- Eliminates the need for a massive Q-table.
- Widely used in robotics, autonomous vehicles, and advanced game-playing AI.



### Additional Components of DQN

Deep Q-Learning introduces several techniques to improve learning stability:

- **Experience Replay**
  - Stores previous experiences and randomly samples them during training.

- **Replay Memory**
  - Maintains a buffer of past experiences for efficient learning.

- **Target Network**
  - Uses a separate neural network to produce stable target Q-values.

- **Mini-batch Training**
  - Updates the neural network using batches of experiences rather than one at a time.

These techniques reduce correlations between consecutive experiences and make learning more stable and efficient.




## Multi-Agent Reinforcement Learning (Two-Agent Case)

The Q-Learning example discussed in this lab assumes **a single agent** interacting with the environment. However, many real-world applications involve **multiple agents** operating simultaneously. This scenario is known as **Multi-Agent Reinforcement Learning (MARL)**.

In a two-agent environment, each agent observes the environment, selects actions, receives rewards, and updates its own policy. The behaviour of one agent can influence the environment experienced by the other, making the learning process more dynamic and challenging.

### How Two Agents Work

Assume there are two agents:

- **Agent A**
- **Agent B**

At each time step:

1. Both agents observe the current state (or their own observations).
2. Each agent independently selects an action.
3. The environment executes both actions.
4. The environment transitions to a new state.
5. Each agent receives a reward (shared or individual).
6. Each agent updates its own Q-values (or neural network in DQN).

The learning process continues until both agents learn an optimal strategy.



## Types of Multi-Agent Learning

### 1. Cooperative Learning

Both agents work together toward the same objective and usually share the same reward.

**Example:**
- Two rescue robots searching a disaster area.
- Multiple warehouse robots moving packages.
- Autonomous drones mapping an affected region.

In this case:

- Both agents cooperate.
- They avoid interfering with each other.
- The goal is to maximise the team's total reward.



### 2. Competitive Learning

Each agent has its own objective, and one agent's success may reduce the reward of the other.

**Examples:**

- Chess
- Football
- Robot combat
- Autonomous racing

Each agent continuously adapts its strategy while learning from the opponent's behaviour.



### 3. Mixed Cooperative-Competitive Learning

Some agents cooperate within a team while competing against another team.

**Example:**

- Robot soccer
- Multi-drone surveillance
- Team-based strategy games

Agents collaborate with teammates but compete against opposing agents.



## Q-Learning with Two Agents

If traditional Q-Learning is used, each agent generally maintains its own Q-table.

For example:

### Agent A

```text
State → Action → Q-value
```

### Agent B

```text
State → Action → Q-value
```

Both agents update their Q-values independently using the Q-Learning equation:

\[
Q(s,a)=Q(s,a)+\alpha\left[R+\gamma\max_{a'}Q(s',a')-Q(s,a)\right]
\]

However, because both agents are learning simultaneously, the environment keeps changing. As one agent improves its policy, it changes the experiences of the other agent. This makes learning more difficult than in the single-agent case.



## Two Agents in Deep Q-Learning

For large environments, each agent can use its own **Deep Q-Network (DQN)** instead of a Q-table.

Each agent maintains:

- A separate Deep Neural Network (DNN)
- Its own replay memory
- A target network
- Experience replay mechanism

The agents train independently while interacting with the same environment.



## Challenges of Multi-Agent Reinforcement Learning

Compared with single-agent learning, multi-agent systems introduce additional challenges:

- The environment changes continuously because all agents are learning.
- Agents must learn to cooperate or compete effectively.
- Learning may take longer to converge.
- Coordination between agents can be difficult.
- More computational resources are required.



## Applications of Multi-Agent Reinforcement Learning

Multi-Agent Reinforcement Learning is widely used in:

- Multi-robot systems
- Autonomous vehicle coordination
- Drone swarms
- Warehouse automation
- Robot soccer
- Traffic signal optimisation
- Smart manufacturing
- Resource allocation in communication networks


## Summary

| Single-Agent Reinforcement Learning | Multi-Agent Reinforcement Learning |
|-------------------------------------|------------------------------------|
| One learning agent | Two or more learning agents |
| Environment remains relatively stable | Environment changes as other agents learn |
| One Q-table or one DQN | Separate Q-table or DQN for each agent |
| Simpler learning process | More complex due to interactions between agents |
| Suitable for individual tasks | Suitable for cooperative, competitive, or mixed tasks |


In [1]:
import numpy as np
import random

# ==========================================
# Grid World Environment
# ==========================================

GRID_SIZE = 4

START = (0, 0)        # S0
GOAL = (3, 3)         # S15

# Obstacles (example)
OBSTACLES = [(1, 1), (2, 1)]

# Actions
actions = {
    0: (-1, 0),   # Up
    1: (1, 0),    # Down
    2: (0, -1),   # Left
    3: (0, 1)     # Right
}

# Q-table
Q = np.zeros((GRID_SIZE, GRID_SIZE, 4))

# Hyperparameters
alpha = 0.1          # Learning Rate
gamma = 0.9          # Discount Factor
epsilon = 0.2        # Exploration Rate

episodes = 1000


# ==========================================
# Reward Function
# ==========================================

def get_reward(state):

    if state == GOAL:
        return 100

    if state in OBSTACLES:
        return -100

    return -1


# ==========================================
# Check Valid Move
# ==========================================

def valid_state(state):

    x, y = state

    if x < 0 or x >= GRID_SIZE:
        return False

    if y < 0 or y >= GRID_SIZE:
        return False

    if state in OBSTACLES:
        return False

    return True


# ==========================================
# Choose Action (Epsilon-Greedy)
# ==========================================

def choose_action(state):

    if random.uniform(0, 1) < epsilon:
        return random.randint(0, 3)

    x, y = state
    return np.argmax(Q[x, y])


# ==========================================
# Training
# ==========================================

for episode in range(episodes):

    state = START

    while state != GOAL:

        action = choose_action(state)

        move = actions[action]

        next_state = (
            state[0] + move[0],
            state[1] + move[1]
        )

        if not valid_state(next_state):
            next_state = state

        reward = get_reward(next_state)

        x, y = state
        nx, ny = next_state

        old_q = Q[x, y, action]

        next_max = np.max(Q[nx, ny])

        # Q-learning update
        Q[x, y, action] = old_q + alpha * (
            reward + gamma * next_max - old_q
        )

        state = next_state


# ==========================================
# Print Learned Policy
# ==========================================

symbols = {
    0: "↑",
    1: "↓",
    2: "←",
    3: "→"
}

print("\nLearned Policy\n")

for i in range(GRID_SIZE):

    for j in range(GRID_SIZE):

        if (i, j) == GOAL:
            print(" G ", end=" ")

        elif (i, j) in OBSTACLES:
            print(" X ", end=" ")

        else:
            best = np.argmax(Q[i, j])
            print(f" {symbols[best]} ", end=" ")

    print()


print("\nQ-table\n")
print(Q)


Learned Policy

 ↓   ←   ↓   ↓  
 ↓   X   ↓   ↓  
 ↓   X   ↓   ↓  
 →   →   →   G  

Q-table

[[[ 48.37730302  54.9539      48.38645408  40.99957774]
  [  3.38048128   1.06931003  48.1526174    0.48330737]
  [ -0.58035826   9.01957217  -0.59338052  -0.54756001]
  [ -0.3940399   -0.382141    -0.41437171  -0.3940399 ]]

 [[ 48.36832545  62.171       54.92169048  54.80677888]
  [  0.           0.           0.           0.        ]
  [ -0.31169741  53.06910031   0.99626041   0.1462382 ]
  [ -0.296929     6.862841    -0.2071      -0.199     ]]

 [[ 54.89170746  70.19        61.98359309  62.0702351 ]
  [  0.           0.           0.           0.        ]
  [ 19.66024762  88.77486922  14.34527727   3.58559   ]
  [ -0.1         46.8559       0.          -0.1       ]]

 [[ 62.06637932  69.92434091  70.13250697  79.1       ]
  [ 78.85117117  76.61812316  69.63490904  89.        ]
  [ 77.60097025  88.35813667  78.21625775 100.        ]
  [  0.           0.           0.           0.        ]]]


## Discussion

A single-agent Q-Learning algorithm was implemented in a Grid World environment. The agent started with an empty Q-table and learned the optimal path from the start state to the goal state through repeated interactions with the environment. During each episode, the agent selected actions, received rewards, and updated the Q-values using the Q-Learning update equation.

Initially, the agent explored different paths randomly, resulting in many inefficient moves. As training progressed, the Q-values converged, enabling the agent to identify the best action for each state. Positive rewards encouraged the agent to move toward the goal, while negative rewards discouraged invalid moves and obstacle states. The learned policy demonstrated that the agent successfully found the shortest and most rewarding path to the goal.

The implementation also highlighted the advantages and limitations of traditional Q-Learning. While it is simple to implement and performs well in small environments such as the 4×4 Grid World, it becomes impractical for larger state spaces due to the increasing size of the Q-table. This limitation motivates the use of Deep Q-Learning (DQN), which replaces the Q-table with a neural network for more complex problems. Furthermore, extending the implementation to a two-agent system would require each agent to maintain its own Q-table or Deep Q-Network and learn while interacting with the same environment, introducing cooperation, competition, and additional learning complexity.



## Conclusion

The implementation successfully demonstrated a single-agent Q-Learning algorithm using a Grid World environment. The agent learned the optimal policy through trial and error by updating its Q-values based on rewards received from the environment. After sufficient training episodes, the agent was able to navigate efficiently from the start state to the goal while avoiding obstacles.

The implementation provided a practical understanding of Markov Decision Processes, reinforcement learning, and the Q-Learning update mechanism. It also showed that although Q-Learning is effective for small and discrete environments, more advanced methods such as Deep Q-Learning are required for large and complex real-world applications. In addition, concepts of Multi-Agent Reinforcement Learning were explored theoretically, demonstrating how multiple agents can cooperate or compete while learning independently within the same environment.